services:
  server:
    build:
      context: .
      target: final
    ports:
      - 5000:5000
    environment:
      - REDIS_HOST=db:6379
    depends_on:
      - db 

  db:
    image: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

volumes:
  redis-data:

