apiVersion: apps/v1
kind: Deployment
metadata:
  name: visitorz-deployment
  labels:
    app: visitorz
spec:
  replicas: 3
  selector:
    matchLabels:
      app: visitorz
  template:
    metadata:
      labels:
        app: visitorz
    spec:
      containers:
      - name: visitorz
        image: ssouthcity/visitorz:latest
        ports:
        - containerPort: 5000
        env:
        - name: REDIS_HOST
          value: redis-service:6379
